---
- name: Install MongoDB
  hosts: database 
  gather_facts: false 
  become: true

  tasks: 
  - name: Clone git to local server 
    ansible.builtin.git:
      repo: https://github.com/angelavuong/acm-aap-demo/
      dest: /home/ec2-user/
    



