---
- name: Install MongoDB
  hosts: database 
  gather_facts: false 
  become: true

  tasks: 
  - name: Install git 
    ansible.builtin.package:
      name: git
      state: present 
      
  - name: Clone git to local server 
    ansible.builtin.git:
      repo: https://github.com/angelavuong/acm-aap-demo/
      dest: /home/ec2-user/acm-aap-demo/

  - name: Copy MongoDB file to repo directory 
    ansible.builtin.copy:
      remote_src: true
      src: /home/ec2-user/acm-aap-demo/mongodb-org-6.0.repo 
      dest: /etc/yum.repos.d/mongodb-org-6.0.repo 
      
  - name: Install package mongodb-org
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: Start mongodb
    ansible.builtin.service:
    name: mongod
    state: started
    



